# https://www.mermaidchart.com/app/projects/ffe65222-4209-4fef-bee5-883f569b7bd5/diagrams/1ab5a820-77ac-4fb9-804d-fc36a56bf0e3/version/v0.1/edit
---
config:
  layout: fixed
---
flowchart TB
    createProject["Create Project"] --> defineAccessControl["Define Access Control"] & prepareData["Prepare Data"]
    projectAdmin["Project Admin"] --> defineAccessControl
    defineAccessControl --> reviewProject["Review Project"]
    reviewProject --> uploadData["Upload Data"]
    validateData["Validate Data"] --> uploadData
    uploadData --> privateDataAccess["Private Data Access"]
    contributor["Contributor"] --> prepareData & validateData & privateDataAccess
    prepareData --> validateData
    projectOwner["Project Owner"] --> createProject & addAdministrator["Add Administrator"] & addContributor["Add Contributor"]
    addAdministrator <--> addContributor
    addAdministrator --> contributor
    emberAdmin["EMBER Admin"] --> reviewProject
    n1["n1"]
    projectAdmin@{ shape: rect}
    contributor@{ shape: rect}
    projectOwner@{ shape: rect}
    addAdministrator@{ shape: trap-b}
    addContributor@{ shape: trap-b}
    emberAdmin@{ shape: rect}
    n1@{ shape: anchor}
     prepareData:::role
     validateData:::role
     privateDataAccess:::role
     addAdministrator:::optional
     addContributor:::optional
    classDef default fill:#fff,stroke:#333,stroke-width:2px
    classDef optional fill:#bbb,stroke:#333,stroke-width:2px
    style Class_III color:#D50000
