---
config:
  layout: fixed
---
flowchart TB
    addContributor["Add Contributor"] --> contributor["Contributor"]
    projectowner["Project Owner"] --> addTitle["Add Title"] & addDescription["Add Description"] & addLicense["Add License"] 
    addRegistrationPublic["Register Dandiset (Public)"] & addRegistrationPrivate["Register Dandiset (Embargoed/Private)"] 
    addRegistrationPrivate & addRegistrationPublic--> prepareData["Prepare Data"]
    addTitle["Add Title"] & addDescription["Add Description"] & addLicense["Add License"] -->  addRegistrationPublic & addRegistrationPrivate 
    prepareData --> convertNWB["Convert Data to NWB"] & convertBIDS["Convert Data to BIDS"]
    convertNWB["Convert Data to NWB"] & convertBIDS["Convert Data to BIDS"]--> validateData["Validate Data"]
    projectAdmin["Project Administrators"] --> userApproval["User Approval"] & userManagement["User Management"]
    emberadmin["EMBER Admin"] --> uploadData["Upload Data"]
    uploadData --> publishMetadata["Publish Metadata"] & privateDataAccess["Private Data Access"]
    publishMetadata --> userApproval
    userApproval --> userManagement
    uploadData <--> Userdataaccess["User Data Access (Read)"]
    authorizedEndUser["Authorized End User (With Account)"] --> userApplication["User Application"] & Userdataaccess
    userApplication --> userApproval
    contributor --> privateDataAccess
    validateData --> uploadData
    addContributor@{ shape: trap-b}
    userApproval@{ shape: trap-b}
    userManagement@{ shape: trap-b}
    prepareData@{ shape: trap-b}
    uploadData@{ shape: trap-b}
    privateDataAccess@{ shape: trap-b}
    userApplication@{ shape: trap-b}
    validateData@{ shape: trap-b}
    n1@{ shape: anchor}
    n2@{ shape: anchor}
    n3@{ shape: anchor}
    n4@{ shape: anchor}
     prepareData:::role
     privateDataAccess:::role
    addRegistrationPrivate:::optional
     validateData:::role
    classDef default fill:#fff,stroke:#333,stroke-width:2px
    classDef optional fill:#bbb,stroke:#333,stroke-width:2px
    style Class_II color:#D50000