---
config:
  layout: fixed
---
flowchart TB
    createProject["Create Project"] --> defineAccessControl["Define Access Control"] & prepareData["Prepare Data"]
    projectowner["Project Owner"] --> addTitle["Add Title"] & addDescription["Add Description"] & addLicense["Add License"] 
    addTitle["Add Title"] & addDescription["Add Description"] & addLicense["Add License"] -->createProject
    defineAccessControl --> reviewProject["Review Project"]
    reviewProject --> uploadData["Upload Data"]
    validateData["Validate Data"] --> uploadData
    uploadData --> privateDataAccess["Private Data Access"]
    prepareData --> validateData
    emberAdmin["EMBER Admin"] --> reviewProject
    projectAdmin@{ shape: rect}
    contributor@{ shape: rect}
    projectOwner@{ shape: rect}
    emberAdmin@{ shape: rect}
    n1@{ shape: anchor}
     prepareData:::role
     validateData:::role
     privateDataAccess:::role
    classDef default fill:#fff,stroke:#333,stroke-width:2px
    classDef optional fill:#bbb,stroke:#333,stroke-width:2px
    style Class_III color:#D50000
